// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TaskCreate = {
    title: string;
    description?: (string | null);
};

export type TaskItem = {
    title: string;
    description?: (string | null);
    created_by_id: string;
    created_at: string;
    edited_at?: (string | null);
    edited_by_id?: (string | null);
    id: string;
    total_amount?: string;
};

export type TaskItems = {
    data: Array<TaskItem>;
    count: number;
};

export type TaskUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WorkLogEntries = {
    data: Array<WorkLogEntryItem>;
    count: number;
};

export type WorkLogEntryBulkDelete = {
    entry_ids: Array<(string)>;
};

export type WorkLogEntryBulkPaymentInitiate = {
    entry_ids: Array<(string)>;
};

export type WorkLogEntryCreate = {
    title: string;
    description?: (string | null);
    task_id: string;
    start_time?: string;
    end_time?: string;
    amount?: (number | string);
};

export type WorkLogEntryItem = {
    title: string;
    description?: (string | null);
    created_by_id: string;
    created_at?: string;
    edited_at?: (string | null);
    edited_by_id?: (string | null);
    id: string;
    task_id: string;
    start_time: string;
    end_time: string;
    amount: string;
    approved: boolean;
    approved_date?: (string | null);
    approved_by_id: (string | null);
    payment_initiated: boolean;
    payment_initiated_date?: (string | null);
    initiated_by_id: (string | null);
    payment_date?: (string | null);
    paid: boolean;
};

export type WorkLogEntryUpdate = {
    title: string;
    description?: (string | null);
    task_id: string;
    start_time?: string;
    end_time?: string;
    amount?: (number | string);
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TasksReadWorkLogsData = {
    endTime?: (string | null);
    limit?: number;
    skip?: number;
    startTime?: (string | null);
    taskId: string;
};

export type TasksReadWorkLogsResponse = (WorkLogEntries);

export type TasksCreateWorkLogData = {
    requestBody: WorkLogEntryCreate;
    taskId: string;
};

export type TasksCreateWorkLogResponse = (WorkLogEntryItem);

export type TasksReadWorkLogData = {
    taskId: string;
    workLogId: string;
};

export type TasksReadWorkLogResponse = (WorkLogEntryItem);

export type TasksUpdateWorkLogData = {
    requestBody: WorkLogEntryUpdate;
    taskId: string;
    workLogId: string;
};

export type TasksUpdateWorkLogResponse = (WorkLogEntryItem);

export type TasksDeleteWorkLogData = {
    taskId: string;
    workLogId: string;
};

export type TasksDeleteWorkLogResponse = (Message);

export type TasksApproveWorkLogData = {
    taskId: string;
    workLogId: string;
};

export type TasksApproveWorkLogResponse = (WorkLogEntryItem);

export type TasksInitiatePaymentData = {
    taskId: string;
    workLogId: string;
};

export type TasksInitiatePaymentResponse = (WorkLogEntryItem);

export type TasksReadAllWorkLogsData = {
    endTime?: (string | null);
    limit?: number;
    skip?: number;
    startTime?: (string | null);
};

export type TasksReadAllWorkLogsResponse = (WorkLogEntries);

export type TasksInitiatePaymentsData = {
    requestBody: WorkLogEntryBulkPaymentInitiate;
};

export type TasksInitiatePaymentsResponse = (Message);

export type TasksBulkDeleteData = {
    requestBody: WorkLogEntryBulkDelete;
};

export type TasksBulkDeleteResponse = (Message);

export type TasksReadTasksData = {
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    startDate?: (string | null);
};

export type TasksReadTasksResponse = (TaskItems);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskItem);

export type TasksReadTaskData = {
    taskId: string;
};

export type TasksReadTaskResponse = (TaskItem);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (TaskItem);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);