// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    hourly_rate?: (number | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    hourly_rate?: (number | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    hourly_rate?: (number | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

// ---------------------------------------------------------------------------
// Worklog types
// ---------------------------------------------------------------------------

export type WorklogCreate = {
    title: string;
    description?: (string | null);
};

export type TimeEntryPublic = {
    start_time: string;
    end_time: string;
    description?: (string | null);
    id: string;
    worklog_id: string;
    hours: number;
    created_at: string;
};

export type WorklogPublic = {
    title: string;
    description?: (string | null);
    id: string;
    freelancer_id: string;
    freelancer_name?: (string | null);
    hourly_rate: number;
    total_hours: number;
    total_earned: number;
    created_at: string;
};

export type WorklogDetail = WorklogPublic & {
    time_entries: Array<TimeEntryPublic>;
};

export type WorklogsPublic = {
    data: Array<WorklogPublic>;
    count: number;
};

export type WorklogsReadWorklogsData = {
    skip?: number;
    limit?: number;
    dateFrom?: (string | null);
    dateTo?: (string | null);
};

export type WorklogsReadWorklogsResponse = (WorklogsPublic);

export type WorklogsReadWorklogData = {
    worklogId: string;
};

export type WorklogsReadWorklogResponse = (WorklogDetail);

export type WorklogsCreateWorklogData = {
    requestBody: WorklogCreate;
};

export type WorklogsCreateWorklogResponse = (WorklogPublic);

// ---------------------------------------------------------------------------
// Payment types
// ---------------------------------------------------------------------------

export type PaymentBatchCreate = {
    date_from: string;
    date_to: string;
};

export type EligibleEntry = {
    time_entry_id: string;
    worklog_id: string;
    worklog_title: string;
    freelancer_id: string;
    freelancer_name?: (string | null);
    hours: number;
    hourly_rate: number;
    amount: number;
    start_time: string;
    end_time: string;
};

export type PaymentBatchPublic = {
    id: string;
    date_from: string;
    date_to: string;
    status: string;
    created_by_id: string;
    total_amount?: (number | null);
    created_at: string;
    confirmed_at?: (string | null);
};

export type PaymentBatchDetail = PaymentBatchPublic & {
    eligible_entries: Array<EligibleEntry>;
    payment_lines: Array<EligibleEntry>;
};

export type PaymentBatchesPublic = {
    data: Array<PaymentBatchPublic>;
    count: number;
};

export type ConfirmBatchIn = {
    excluded_worklog_ids?: Array<string>;
    excluded_freelancer_ids?: Array<string>;
};

export type PaymentsReadBatchesData = {
    skip?: number;
    limit?: number;
};

export type PaymentsReadBatchesResponse = (PaymentBatchesPublic);

export type PaymentsCreateBatchData = {
    requestBody: PaymentBatchCreate;
};

export type PaymentsCreateBatchResponse = (PaymentBatchDetail);

export type PaymentsReadBatchData = {
    batchId: string;
};

export type PaymentsReadBatchResponse = (PaymentBatchDetail);

export type PaymentsConfirmBatchData = {
    batchId: string;
    requestBody: ConfirmBatchIn;
};

export type PaymentsConfirmBatchResponse = (PaymentBatchPublic);

export type PaymentsDeleteBatchData = {
    batchId: string;
};

export type PaymentsDeleteBatchResponse = (Message);