// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TaskCreate = {
    title: string;
    description?: (string | null);
};

export type TaskPublic = {
    title: string;
    description?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type TimeEntriesPublic = {
    data: Array<TimeEntryPublic>;
    count: number;
};

export type TimeEntryCreate = {
    task_id: string;
    start_time: string;
    end_time: string;
    description?: (string | null);
};

export type TimeEntryPublic = {
    task_id: string;
    start_time: string;
    end_time: string;
    description?: (string | null);
    id: string;
    freelancer_id: string;
    freelancer_name: string;
    created_at: string;
    task_title: string;
};

export type TimeEntryUpdate = {
    task_id?: (string | null);
    start_time?: (string | null);
    end_time?: (string | null);
    description?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    hourly_rate?: (number | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    hourly_rate?: (number | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'ADMIN' | 'FREELANCER';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    hourly_rate?: (number | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type PaymentBatchStatus = 'DRAFT' | 'CONFIRMED';

export type PaymentBatchCreate = {
    date_from: string;
    date_to: string;
};

export type PaymentBatchPublic = {
    id: string;
    created_by_id: string;
    date_from: string;
    date_to: string;
    status: PaymentBatchStatus;
    total_amount: number;
    created_at: string;
    confirmed_at: (string | null);
};

export type PaymentBatchesPublic = {
    data: Array<PaymentBatchPublic>;
    count: number;
};

export type EligibleTimeEntry = {
    time_entry_id: string;
    task_id: string;
    task_title: string;
    freelancer_id: string;
    freelancer_name: string;
    start_time: string;
    end_time: string;
    hours: number;
    hourly_rate: number;
    amount: number;
};

export type PaymentBatchDetail = {
    batch: PaymentBatchPublic;
    eligible_entries: Array<EligibleTimeEntry>;
};

export type PaymentPublic = {
    id: string;
    batch_id: string;
    freelancer_id: string;
    freelancer_name: string;
    time_entry_id: string;
    task_title: string;
    hours: number;
    hourly_rate: number;
    amount: number;
    created_at: string;
};

export type PaymentsPublic = {
    data: Array<PaymentPublic>;
    count: number;
};

export type PaymentsReadBatchesData = { skip?: number; limit?: number };
export type PaymentsReadBatchesResponse = PaymentBatchesPublic;
export type PaymentsCreateBatchData = { requestBody: PaymentBatchCreate };
export type PaymentsCreateBatchResponse = PaymentBatchDetail;
export type PaymentsReadBatchData = { batchId: string };
export type PaymentsReadBatchResponse = PaymentBatchDetail;
export type PaymentsReadBatchPaymentsData = { batchId: string };
export type PaymentsReadBatchPaymentsResponse = PaymentsPublic;
export type PaymentsConfirmBatchData = { batchId: string; requestBody: Array<string> };
export type PaymentsConfirmBatchResponse = PaymentBatchPublic;
export type PaymentsDeleteBatchData = { batchId: string };
export type PaymentsDeleteBatchResponse = unknown;

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TasksReadTasksData = {
    limit?: number;
    skip?: number;
};

export type TasksReadTasksResponse = (TasksPublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksReadTaskData = {
    id: string;
};

export type TasksReadTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    id: string;
    requestBody: TaskUpdate;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    id: string;
};

export type TasksDeleteTaskResponse = (Message);

export type TimeEntriesReadTimeEntriesData = {
    limit?: number;
    skip?: number;
};

export type TimeEntriesReadTimeEntriesResponse = (TimeEntriesPublic);

export type TimeEntriesCreateTimeEntryData = {
    requestBody: TimeEntryCreate;
};

export type TimeEntriesCreateTimeEntryResponse = (TimeEntryPublic);

export type TimeEntriesReadTimeEntryData = {
    id: string;
};

export type TimeEntriesReadTimeEntryResponse = (TimeEntryPublic);

export type TimeEntriesUpdateTimeEntryData = {
    id: string;
    requestBody: TimeEntryUpdate;
};

export type TimeEntriesUpdateTimeEntryResponse = (TimeEntryPublic);

export type TimeEntriesDeleteTimeEntryData = {
    id: string;
};

export type TimeEntriesDeleteTimeEntryResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorklogSummary = {
    task_id: string;
    task_title: string;
    freelancer_id: string;
    freelancer_name: string;
    total_hours: number;
    total_amount: number;
    entry_count: number;
};

export type WorklogsSummary = {
    data: Array<WorklogSummary>;
    count: number;
};

export type WorklogsReadWorklogsSummaryData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    freelancerId?: (string | null);
};

export type WorklogsReadWorklogsSummaryResponse = (WorklogsSummary);