"""Implement advanced settlement logic

Revision ID: 4ba388311a78
Revises: 33e721acb246
Create Date: 2026-01-29 01:27:40.182873

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ba388311a78'
down_revision = '33e721acb246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    conn = op.get_bind()
    
    # Create enums manually if they don't exist
    res = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'adjustmentstatus'")).first()
    if not res:
        op.execute("CREATE TYPE adjustmentstatus AS ENUM ('PENDING', 'PAID', 'CANCELLED')")
    
    res = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'taskstatusstate'")).first()
    if not res:
        op.execute("CREATE TYPE taskstatusstate AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')")

    # Update remittancestate
    op.execute("ALTER TYPE remittancestate ADD VALUE IF NOT EXISTS 'AWAITING_APPROVAL'")
    op.execute("ALTER TYPE remittancestate ADD VALUE IF NOT EXISTS 'OFFSET'")
    op.execute("ALTER TYPE remittancestate ADD VALUE IF NOT EXISTS 'AWAITING_FUNDING'")
    
    # Add REJECTED to timesegmentstatus
    op.execute("ALTER TYPE timesegmentstatus ADD VALUE IF NOT EXISTS 'REJECTED'")

    op.create_table('taskstatus',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # Use Postgres specific type name string to avoid auto-creation attempt
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatusstate', create_type=False), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('adjustment', sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'CANCELLED', name='adjustmentstatus', create_type=False), nullable=False, server_default='PENDING'))
    op.add_column('settlementrun', sa.Column('task_id', sa.Uuid(), nullable=True))
    op.add_column('task', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['created_by_id'], ['id'])
    op.add_column('timesegment', sa.Column('rate_at_recording', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('wallet', sa.Column('reserve', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'reserve')
    op.drop_column('timesegment', 'rate_at_recording')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'created_by_id')
    op.drop_column('settlementrun', 'task_id')
    op.drop_column('adjustment', 'status')
    op.drop_table('taskstatus')
    # ### end Alembic commands ###