"""Add tasks and worklogs

Revision ID: 6d8214aa2d3a
Revises: 1a31ce608336
Create Date: 2026-02-11 04:25:35.339592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d8214aa2d3a'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['edited_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worklogentry',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('payment_initiated', sa.Boolean(), nullable=False),
    sa.Column('payment_initiated_date', sa.DateTime(), nullable=True),
    sa.Column('initiated_by_id', sa.Uuid(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['edited_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worklogentry')
    op.drop_table('task')
    # ### end Alembic commands ###
