"""Add worklog models

Revision ID: 70f077c04c35
Revises: 1a31ce608336
Create Date: 2026-02-09 07:40:09.822394

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '70f077c04c35'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelancer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('rate_per_hour', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelancer_created_at'), 'freelancer', ['created_at'], unique=False)
    op.create_index(op.f('ix_freelancer_email'), 'freelancer', ['email'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worklog_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_freelancer_id'), 'payment', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_payment_payment_date'), 'payment', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_table('worklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worklog_created_at'), 'worklog', ['created_at'], unique=False)
    op.create_index(op.f('ix_worklog_freelancer_id'), 'worklog', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_worklog_status'), 'worklog', ['status'], unique=False)
    op.create_table('timeentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worklog_id', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeentry_entry_date'), 'timeentry', ['entry_date'], unique=False)
    op.create_index(op.f('ix_timeentry_worklog_id'), 'timeentry', ['worklog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeentry_worklog_id'), table_name='timeentry')
    op.drop_index(op.f('ix_timeentry_entry_date'), table_name='timeentry')
    op.drop_table('timeentry')
    op.drop_index(op.f('ix_worklog_status'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_freelancer_id'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_created_at'), table_name='worklog')
    op.drop_table('worklog')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_payment_date'), table_name='payment')
    op.drop_index(op.f('ix_payment_freelancer_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_freelancer_email'), table_name='freelancer')
    op.drop_index(op.f('ix_freelancer_created_at'), table_name='freelancer')
    op.drop_table('freelancer')
    # ### end Alembic commands ###
