"""add_settlement_tables

Revision ID: 7688dd5ef2dc
Revises: 1a31ce608336
Create Date: 2026-02-11 17:15:31.821480

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7688dd5ef2dc'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remittance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_created_at'), 'remittance', ['created_at'], unique=False)
    op.create_index(op.f('ix_remittance_status'), 'remittance', ['status'], unique=False)
    op.create_index(op.f('ix_remittance_user_id'), 'remittance', ['user_id'], unique=False)
    op.create_table('worklog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worklog_created_at'), 'worklog', ['created_at'], unique=False)
    op.create_index(op.f('ix_worklog_status'), 'worklog', ['status'], unique=False)
    op.create_index(op.f('ix_worklog_user_id'), 'worklog', ['user_id'], unique=False)
    op.create_table('adjustment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worklog_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjustment_created_at'), 'adjustment', ['created_at'], unique=False)
    op.create_index(op.f('ix_adjustment_status'), 'adjustment', ['status'], unique=False)
    op.create_index(op.f('ix_adjustment_worklog_id'), 'adjustment', ['worklog_id'], unique=False)
    op.create_table('remittance_worklog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remittance_id', sa.Uuid(), nullable=False),
    sa.Column('worklog_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittance.id'], ),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_worklog_remittance_id'), 'remittance_worklog', ['remittance_id'], unique=False)
    op.create_index(op.f('ix_remittance_worklog_worklog_id'), 'remittance_worklog', ['worklog_id'], unique=False)
    op.create_table('time_segment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worklog_id', sa.Uuid(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_segment_created_at'), 'time_segment', ['created_at'], unique=False)
    op.create_index(op.f('ix_time_segment_status'), 'time_segment', ['status'], unique=False)
    op.create_index(op.f('ix_time_segment_worklog_id'), 'time_segment', ['worklog_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_segment_worklog_id'), table_name='time_segment')
    op.drop_index(op.f('ix_time_segment_status'), table_name='time_segment')
    op.drop_index(op.f('ix_time_segment_created_at'), table_name='time_segment')
    op.drop_table('time_segment')
    op.drop_index(op.f('ix_remittance_worklog_worklog_id'), table_name='remittance_worklog')
    op.drop_index(op.f('ix_remittance_worklog_remittance_id'), table_name='remittance_worklog')
    op.drop_table('remittance_worklog')
    op.drop_index(op.f('ix_adjustment_worklog_id'), table_name='adjustment')
    op.drop_index(op.f('ix_adjustment_status'), table_name='adjustment')
    op.drop_index(op.f('ix_adjustment_created_at'), table_name='adjustment')
    op.drop_table('adjustment')
    op.drop_index(op.f('ix_worklog_user_id'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_status'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_created_at'), table_name='worklog')
    op.drop_table('worklog')
    op.drop_index(op.f('ix_remittance_user_id'), table_name='remittance')
    op.drop_index(op.f('ix_remittance_status'), table_name='remittance')
    op.drop_index(op.f('ix_remittance_created_at'), table_name='remittance')
    op.drop_table('remittance')
    # ### end Alembic commands ###
