"""add_payment_status_to_timeentry

Revision ID: 8d50e1d01ec9
Revises: b2c3d4e5f6g7
Create Date: 2026-02-03 18:53:37.742470

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "8d50e1d01ec9"
down_revision = "b2c3d4e5f6g7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column(
        "timeentry",
        sa.Column("payment_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "timeentry",
        sa.Column("paid_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "timeentry",
        sa.Column(
            "payment_batch_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )

    # Set default value for existing rows
    op.execute(
        "UPDATE timeentry SET payment_status = 'unpaid' WHERE payment_status IS NULL"
    )

    # Now make payment_status NOT NULL
    op.alter_column("timeentry", "payment_status", nullable=False)

    # Create indexes
    op.create_index(
        op.f("ix_timeentry_payment_batch_id"),
        "timeentry",
        ["payment_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timeentry_payment_status"),
        "timeentry",
        ["payment_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timeentry_payment_status"), table_name="timeentry")
    op.drop_index(op.f("ix_timeentry_payment_batch_id"), table_name="timeentry")
    op.drop_column("timeentry", "payment_batch_id")
    op.drop_column("timeentry", "paid_at")
    op.drop_column("timeentry", "payment_status")
    # ### end Alembic commands ###
