"""models change

Revision ID: bf4ee0534c19
Revises: cc29e5d99ab3
Create Date: 2026-01-28 20:42:54.658845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf4ee0534c19'
down_revision: Union[str, Sequence[str], None] = 'cc29e5d99ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('remittance',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('total_amount', sa.Float(), nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('period_start', sa.Date(), nullable=False),
                    sa.Column('period_end', sa.Date(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('paid_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_remittance_user_id'),
                    'remittance', ['user_id'], unique=False)
    op.create_table('worklog',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('task_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_worklog_task_id'),
                    'worklog', ['task_id'], unique=False)
    op.create_index(op.f('ix_worklog_user_id'),
                    'worklog', ['user_id'], unique=False)
    op.create_table('adjustment',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('worklog_id', sa.Uuid(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('remittanceworklog',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('remittance_id', sa.Uuid(), nullable=False),
                    sa.Column('worklog_id', sa.Uuid(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['remittance_id'], ['remittance.id'], ),
                    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('timesegment',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('worklog_id', sa.Uuid(), nullable=False),
                    sa.Column('start', sa.DateTime(), nullable=False),
                    sa.Column('end', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['worklog_id'], ['worklog.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesegment')
    op.drop_table('remittanceworklog')
    op.drop_table('adjustment')
    op.drop_index(op.f('ix_worklog_user_id'), table_name='worklog')
    op.drop_index(op.f('ix_worklog_task_id'), table_name='worklog')
    op.drop_table('worklog')
    op.drop_index(op.f('ix_remittance_user_id'), table_name='remittance')
    op.drop_table('remittance')
    op.drop_table('task')
    # ### end Alembic commands ###
