"""add hourly_rate to worklog 2

Revision ID: d81ac961ee4c
Revises: 12f30676808e
Create Date: 2026-02-02 14:10:36.797092

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd81ac961ee4c'
down_revision = '12f30676808e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
