"""add rejected status to timesegmentstatus enum

Revision ID: dafd9df48c1d
Revises: 4ba388311a78
Create Date: 2026-01-29 03:11:02.860472

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dafd9df48c1d'
down_revision = '4ba388311a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
