/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as FreelancerLayoutRouteImport } from './routes/_freelancer-layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutWorklogsRouteImport } from './routes/_layout/worklogs'
import { Route as LayoutPaymentHistoryRouteImport } from './routes/_layout/payment-history'
import { Route as LayoutPaymentReviewRouteImport } from './routes/_layout/payment-review'
import { Route as FreelancerLoginRouteImport } from './routes/freelancer/login'
import { Route as FreelancerRegisterRouteImport } from './routes/freelancer/register'
import { Route as FreelancerLayoutIndexRouteImport } from './routes/_freelancer-layout/index'
import { Route as FreelancerLayoutWorklogsRouteImport } from './routes/_freelancer-layout/worklogs'
import { Route as FreelancerLayoutPaymentsRouteImport } from './routes/_freelancer-layout/payments'
import { Route as FreelancerLayoutProfileRouteImport } from './routes/_freelancer-layout/profile'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerLayoutRoute = FreelancerLayoutRouteImport.update({
  id: '/_freelancer-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorklogsRoute = LayoutWorklogsRouteImport.update({
  id: '/worklogs',
  path: '/worklogs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentHistoryRoute = LayoutPaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPaymentReviewRoute = LayoutPaymentReviewRouteImport.update({
  id: '/payment-review',
  path: '/payment-review',
  getParentRoute: () => LayoutRoute,
} as any)
const FreelancerLoginRoute = FreelancerLoginRouteImport.update({
  id: '/freelancer/login',
  path: '/freelancer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerRegisterRoute = FreelancerRegisterRouteImport.update({
  id: '/freelancer/register',
  path: '/freelancer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerLayoutIndexRoute = FreelancerLayoutIndexRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => FreelancerLayoutRoute,
} as any)
const FreelancerLayoutWorklogsRoute = FreelancerLayoutWorklogsRouteImport.update({
  id: '/freelancer/worklogs',
  path: '/freelancer/worklogs',
  getParentRoute: () => FreelancerLayoutRoute,
} as any)
const FreelancerLayoutPaymentsRoute = FreelancerLayoutPaymentsRouteImport.update({
  id: '/freelancer/payments',
  path: '/freelancer/payments',
  getParentRoute: () => FreelancerLayoutRoute,
} as any)
const FreelancerLayoutProfileRoute = FreelancerLayoutProfileRouteImport.update({
  id: '/freelancer/profile',
  path: '/freelancer/profile',
  getParentRoute: () => FreelancerLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/worklogs': typeof LayoutWorklogsRoute
  '/payment-history': typeof LayoutPaymentHistoryRoute
  '/payment-review': typeof LayoutPaymentReviewRoute
  '/': typeof LayoutIndexRoute
  '/freelancer/login': typeof FreelancerLoginRoute
  '/freelancer/register': typeof FreelancerRegisterRoute
  '/freelancer': typeof FreelancerLayoutIndexRoute
  '/freelancer/worklogs': typeof FreelancerLayoutWorklogsRoute
  '/freelancer/payments': typeof FreelancerLayoutPaymentsRoute
  '/freelancer/profile': typeof FreelancerLayoutProfileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/worklogs': typeof LayoutWorklogsRoute
  '/payment-history': typeof LayoutPaymentHistoryRoute
  '/payment-review': typeof LayoutPaymentReviewRoute
  '/': typeof LayoutIndexRoute
  '/freelancer/login': typeof FreelancerLoginRoute
  '/freelancer/register': typeof FreelancerRegisterRoute
  '/freelancer': typeof FreelancerLayoutIndexRoute
  '/freelancer/worklogs': typeof FreelancerLayoutWorklogsRoute
  '/freelancer/payments': typeof FreelancerLayoutPaymentsRoute
  '/freelancer/profile': typeof FreelancerLayoutProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_freelancer-layout': typeof FreelancerLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/worklogs': typeof LayoutWorklogsRoute
  '/_layout/payment-history': typeof LayoutPaymentHistoryRoute
  '/_layout/payment-review': typeof LayoutPaymentReviewRoute
  '/_layout/': typeof LayoutIndexRoute
  '/freelancer/login': typeof FreelancerLoginRoute
  '/freelancer/register': typeof FreelancerRegisterRoute
  '/_freelancer-layout/freelancer': typeof FreelancerLayoutIndexRoute
  '/_freelancer-layout/freelancer/worklogs': typeof FreelancerLayoutWorklogsRoute
  '/_freelancer-layout/freelancer/payments': typeof FreelancerLayoutPaymentsRoute
  '/_freelancer-layout/freelancer/profile': typeof FreelancerLayoutProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/worklogs'
    | '/payment-history'
    | '/payment-review'
    | '/'
    | '/freelancer/login'
    | '/freelancer/register'
    | '/freelancer'
    | '/freelancer/worklogs'
    | '/freelancer/payments'
    | '/freelancer/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/worklogs'
    | '/payment-history'
    | '/payment-review'
    | '/'
    | '/freelancer/login'
    | '/freelancer/register'
    | '/freelancer'
    | '/freelancer/worklogs'
    | '/freelancer/payments'
    | '/freelancer/profile'
  id:
    | '__root__'
    | '/_layout'
    | '/_freelancer-layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/worklogs'
    | '/_layout/payment-history'
    | '/_layout/payment-review'
    | '/_layout/'
    | '/freelancer/login'
    | '/freelancer/register'
    | '/_freelancer-layout/freelancer'
    | '/_freelancer-layout/freelancer/worklogs'
    | '/_freelancer-layout/freelancer/payments'
    | '/_freelancer-layout/freelancer/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  FreelancerLayoutRoute: typeof FreelancerLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  FreelancerLoginRoute: typeof FreelancerLoginRoute
  FreelancerRegisterRoute: typeof FreelancerRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_freelancer-layout': {
      id: '/_freelancer-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof FreelancerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/worklogs': {
      id: '/_layout/worklogs'
      path: '/worklogs'
      fullPath: '/worklogs'
      preLoaderRoute: typeof LayoutWorklogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payment-history': {
      id: '/_layout/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof LayoutPaymentHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/payment-review': {
      id: '/_layout/payment-review'
      path: '/payment-review'
      fullPath: '/payment-review'
      preLoaderRoute: typeof LayoutPaymentReviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/freelancer/login': {
      id: '/freelancer/login'
      path: '/freelancer/login'
      fullPath: '/freelancer/login'
      preLoaderRoute: typeof FreelancerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/register': {
      id: '/freelancer/register'
      path: '/freelancer/register'
      fullPath: '/freelancer/register'
      preLoaderRoute: typeof FreelancerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_freelancer-layout/freelancer': {
      id: '/_freelancer-layout/freelancer'
      path: '/freelancer'
      fullPath: '/freelancer'
      preLoaderRoute: typeof FreelancerLayoutIndexRouteImport
      parentRoute: typeof FreelancerLayoutRoute
    }
    '/_freelancer-layout/freelancer/worklogs': {
      id: '/_freelancer-layout/freelancer/worklogs'
      path: '/freelancer/worklogs'
      fullPath: '/freelancer/worklogs'
      preLoaderRoute: typeof FreelancerLayoutWorklogsRouteImport
      parentRoute: typeof FreelancerLayoutRoute
    }
    '/_freelancer-layout/freelancer/payments': {
      id: '/_freelancer-layout/freelancer/payments'
      path: '/freelancer/payments'
      fullPath: '/freelancer/payments'
      preLoaderRoute: typeof FreelancerLayoutPaymentsRouteImport
      parentRoute: typeof FreelancerLayoutRoute
    }
    '/_freelancer-layout/freelancer/profile': {
      id: '/_freelancer-layout/freelancer/profile'
      path: '/freelancer/profile'
      fullPath: '/freelancer/profile'
      preLoaderRoute: typeof FreelancerLayoutProfileRouteImport
      parentRoute: typeof FreelancerLayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWorklogsRoute: typeof LayoutWorklogsRoute
  LayoutPaymentHistoryRoute: typeof LayoutPaymentHistoryRoute
  LayoutPaymentReviewRoute: typeof LayoutPaymentReviewRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWorklogsRoute: LayoutWorklogsRoute,
  LayoutPaymentHistoryRoute: LayoutPaymentHistoryRoute,
  LayoutPaymentReviewRoute: LayoutPaymentReviewRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface FreelancerLayoutRouteChildren {
  FreelancerLayoutIndexRoute: typeof FreelancerLayoutIndexRoute
  FreelancerLayoutWorklogsRoute: typeof FreelancerLayoutWorklogsRoute
  FreelancerLayoutPaymentsRoute: typeof FreelancerLayoutPaymentsRoute
  FreelancerLayoutProfileRoute: typeof FreelancerLayoutProfileRoute
}

const FreelancerLayoutRouteChildren: FreelancerLayoutRouteChildren = {
  FreelancerLayoutIndexRoute: FreelancerLayoutIndexRoute,
  FreelancerLayoutWorklogsRoute: FreelancerLayoutWorklogsRoute,
  FreelancerLayoutPaymentsRoute: FreelancerLayoutPaymentsRoute,
  FreelancerLayoutProfileRoute: FreelancerLayoutProfileRoute,
}

const FreelancerLayoutRouteWithChildren =
  FreelancerLayoutRoute._addFileChildren(FreelancerLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  FreelancerLayoutRoute: FreelancerLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  FreelancerLoginRoute: FreelancerLoginRoute,
  FreelancerRegisterRoute: FreelancerRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
